create or replace FUNCTION SP_PNS_CALL_RECORD_ACTIV_ARCH() RETURNS VOID AS
$body$
BEGIN
	INSERT INTO PNS_CALL_RECORDS_ACTIVE_ARCH SELECT * FROM PNS_CALL_RECORDS_ACTIVE WHERE DATE(PNS_CALL_START_DATE) < DATE(NOW())-1;
	DELETE FROM PNS_CALL_RECORDS_ACTIVE WHERE DATE(PNS_CALL_START_DATE) < DATE(NOW())-1;


	
	Exception When Others Then
	raise notice 'function has been failed % %', SQLERRM, SQLSTATE;
	raise exception 'function has been failed % %', SQLERRM, SQLSTATE;

END;
$body$
LANGUAGE plpgsql;
